mods.extendedcrafting.TableCrafting.addShaped(<contenttweaker:earth_altar>, [
[<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:quadruply_compressed_cobblestone>,<contenttweaker:life_altar>],
[<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>,<contenttweaker:life_altar>]]);
